modules/Jalousie/models/Jalousie.php
<?php

namespace app\modules\Jalousie\models;

use Yii;
//use yii\base\Model;
use yii\helpers\ArrayHelper;
use yii\caching\TagDependency;

/**
 * This is the model class for table "Jalousie".
 *
 * @property integer $ID
 * @property integer $HasOptions
 * @property string $Type
 *
 * @property JalousieLang $lang
 * @property JalousieLang[] $langs
 */
class Jalousie extends \yii\db\ActiveRecord
{
    
    const TypeOnWindow = 'OnWindow';
    const TypeFrontal = 'Frontal';
    const TypeInternal = 'Internal';

    public $Price = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Jalousie';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Type'], 'required'],
            [['Type'], 'string', 'max' => 50],
            [['HasOptions'], 'integer'],
            [['HasOptions'], 'default', 'value' => 0],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => Yii::t('app', 'ID'),
            'HasOptions' => Yii::t('app', 'Has Options'),
            'Type' => Yii::t('app', 'Type'),
        ];
    }

     /**
     * @return \yii\db\ActiveQuery
     */
    public function getLang()
    {
        return $this->hasOne(JalousieLang::className(), ['JalousieID' => 'ID'])->where(['LangID' => Yii::$app->language]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLangs()
    {
        $langs = $this->hasMany(JalousieLang::className(), ['JalousieID' => 'ID'])->indexBy('LangID')->all();
        
        $result = [];
        foreach (array_keys(Yii::$app->params['languages']) as $key => $langID)
        {
            $result[$key] = isset($langs[$langID]) ? $langs[$langID] : new JalousieLang([
                'LangID' => $langID,
            ]);
        }
        
        return $result;
    }
    
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        
        TagDependency::invalidate(Yii::$app->cache, self::className());
        
        $langModels = [];
        foreach ($this->langs as $langModel)
        {
            $langModel->JalousieID = $this->ID;
            $langModels[] = $langModel;
        }
        
        if (Model::loadMultiple($langModels, Yii::$app->request->post()) && Model::validateMultiple($langModels))
        {
            foreach ($langModels as $langModel)
            {
                $langModel->save();
            }
        }
    }
    
    public static function getTypesList($addEmpty = false)
    {
        $res = $addEmpty ? ['' => $addEmpty] : [];
        
        return $res + [
            self::TypeOnWindow => Yii::t('app', 'On Window'),
            self::TypeFrontal => Yii::t('app', 'Frontal'),
            self::TypeInternal => Yii::t('app', 'Internal'),
        ];
    }
    
    public static function getList($addEmpty = false)
    {
        $res = $addEmpty ? ['' => $addEmpty] : [];
        $models = ArrayHelper::map(self::find()->with(['lang'])->all(), 'ID', 'lang.Title');
        return $res + $models;
    }
    
    public function getModels()
    {
        return $this->hasMany(Model::className(), ['JalousieID' => 'ID'])->with('lang');
    }
    
}

modules/Jalousie/models/JalousieLang.php
<?php

namespace app\modules\Jalousie\models;

use Yii;

/**
 * This is the model class for table "JalousieLang".
 *
 * @property integer $ID
 * @property integer $JalousieID
 * @property string $LangID
 * @property string $Title
 *
 */
class JalousieLang extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'JalousieLang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['JalousieID', 'LangID', 'Title'], 'required'],
            [['JalousieID'], 'integer'],
            [['LangID'], 'string', 'max' => 2],
            [['Title'], 'string', 'max' => 255],
            [['JalousieID'], 'exist', 'skipOnError' => true, 'targetClass' => Jalousie::className(), 'targetAttribute' => ['JalousieID' => 'ID']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => Yii::t('app', 'ID'),
            'JalousieID' => Yii::t('app', 'Jalousie ID'),
            'LangID' => Yii::t('app', 'Lang ID'),
            'Title' => Yii::t('app', 'Title'),
        ];
    }
    
}

modules/Jalousie/models/JalousieSearch.php
<?php

namespace app\modules\Jalousie\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\modules\Jalousie\models\Jalousie;

/**
 * JalousieSearch represents the model behind the search form about `app\modules\Windowsill\models\Jalousie`.
 */
class JalousieSearch extends Jalousie
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ID'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Jalousie::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'ID' => $this->ID,
        ]);

        return $dataProvider;
    }
}

modules/Jalousie/models/MechanismOption.php
<?php

namespace app\modules\Jalousie\models;

use Yii;
//use yii\base\Model;
use yii\helpers\ArrayHelper;
use yii\caching\TagDependency;

/**
 * This is the model class for table "MechanismOption".
 *
 * @property integer $ID
 * @property integer $HasOptions
 * @property string $Type
 *
 * @property MechanismOptionLang $lang
 * @property MechanismOptionLang[] $langs
 */
class MechanismOption extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'MechanismOption';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Price', 'OpeningMechanismID'], 'required'],
            [['Price'], 'number', 'min' => 0],
            [['OpeningMechanismID'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => Yii::t('app', 'ID'),
            'Price' => Yii::t('app', 'Price'),
            'OpeningMechanismID' => Yii::t('app', 'Opening Mechanism'),
        ];
    }

     /**
     * @return \yii\db\ActiveQuery
     */
    public function getLang()
    {
        return $this->hasOne(MechanismOptionLang::className(), ['MechanismOptionID' => 'ID'])->where(['LangID' => Yii::$app->language]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLangs()
    {
        $langs = $this->hasMany(MechanismOptionLang::className(), ['MechanismOptionID' => 'ID'])->indexBy('LangID')->all();
        
        $result = [];
        foreach (array_keys(Yii::$app->params['languages']) as $key => $langID)
        {
            $result[$key] = isset($langs[$langID]) ? $langs[$langID] : new MechanismOptionLang([
                'LangID' => $langID,
            ]);
        }
        
        return $result;
    }
    
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        
        TagDependency::invalidate(Yii::$app->cache, self::className());
        
        $langModels = [];
        foreach ($this->langs as $langModel)
        {
            $langModel->MechanismOptionID = $this->ID;
            $langModels[] = $langModel;
        }
        
        if (Model::loadMultiple($langModels, Yii::$app->request->post()) && Model::validateMultiple($langModels))
        {
            foreach ($langModels as $langModel)
            {
                $langModel->save();
            }
        }
    }
    
    public static function getList($addEmpty = false)
    {
        $res = $addEmpty ? ['' => $addEmpty] : [];
        $models = ArrayHelper::map(self::find()->with(['lang'])->all(), 'ID', 'lang.Title');
        return $res + $models;
    }
    
}

modules/Jalousie/controllers/ModelColorController.php
<?php

namespace app\modules\Jalousie\controllers;

use Yii;
use app\modules\Jalousie\models\ModelColor;
use app\modules\Jalousie\models\ModelColorSearch;
use app\modules\Admin\controllers\AdminController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ModelColorController implements the CRUD actions for ModelColor model.
 */
class ModelColorController extends AdminController
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ModelColor models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ModelColorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ModelColor model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ModelColor model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ModelColor();

        if ($model->load(Yii::$app->request->post()))
        {
            $model->Image = $this->saveImage($model);

            if ($model->save())
            {
                Yii::$app->session->setFlash('success', Yii::t('app', 'Data was saved'));
                return $this->redirect(['model/update', 'id' => $model->ModelID, 'tab' => 'colors']);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ModelColor model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()))
        {
            $model->Image = $this->saveImage($model);

            if ($model->save())
            {
                Yii::$app->session->setFlash('success', Yii::t('app', 'Data was saved'));
                return $this->redirect(['model/update', 'id' => $model->ModelID, 'tab' => 'colors']);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ModelColor model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ModelColor model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ModelColor the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ModelColor::findOne($id)) !== null)
        {
            return $model;
        }
        else
        {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function saveImage($model)
    {
        $uploaded = UploadedFile::getInstanceByName('Image');

        if ($uploaded)
        {
            $fileName = md5(microtime(true)) . '.' . $uploaded->extension;
            if ($uploaded->saveAs(Yii::getAlias('@webroot/uploads/jalousie/' . $fileName)))
            {
                return $fileName;
            }
        }

        return $model->Image;
    }

}

modules/Jalousie/controllers/ModelController.php
<?php

namespace app\modules\Jalousie\controllers;

use Yii;
use app\modules\Jalousie\models\Model;
use app\modules\Jalousie\models\ModelSearch;
use app\modules\Admin\controllers\AdminController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use app\modules\Jalousie\models\ModelColorSearch;

/**
 * ModelController implements the CRUD actions for Model model.
 */
class ModelController extends AdminController
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Model models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ModelSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Model model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Model model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Model();

        if ($model->load(Yii::$app->request->post()))
        {
            $model->Image = $this->saveImage($model);

            if ($model->save())
            {
                Yii::$app->session->setFlash('success', Yii::t('app', 'Data was saved'));
                return $this->redirect(['update', 'id' => $model->ID]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Model model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        $searchModel = new ModelColorSearch();
        $dataProvider = $searchModel->search([
            'ModelID' => $model->ID,
        ]);

        if ($model->load(Yii::$app->request->post()))
        {
            $model->Image = $this->saveImage($model);

            if ($model->save())
            {
                Yii::$app->session->setFlash('success', Yii::t('app', 'Data was saved'));
                return $this->redirect(['update', 'id' => $model->ID]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Deletes an existing Model model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Model model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Model the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Model::findOne($id)) !== null)
        {
            return $model;
        }
        else
        {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function saveImage($model)
    {
        $uploaded = UploadedFile::getInstanceByName('Image');

        if ($uploaded)
        {
            $fileName = md5(microtime(true)) . '.' . $uploaded->extension;
            if ($uploaded->saveAs(Yii::getAlias('@webroot/uploads/jalousie/' . $fileName)))
            {
                return $fileName;
            }
        }

        return $model->Image;
    }

}

modules/Jalousie/views/model/_colors_form.php
<?php

    use yii\widgets\Pjax;
    use yii\bootstrap\Html;
    use app\components\GridView\GridView;

?>

<br />

<p>
    <?= Html::a(Yii::t('app', 'Create Model color'), ['model-color/create', 'modelID' => $model->ID], ['class' => 'btn btn-success']) ?>
</p>

<?php Pjax::begin(); ?>    
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'lang.Title',
            [
                'attribute' => 'Image',
                'format' => 'raw',
                'value' => function($model)
                {
                    return Html::img($model->imagePath, ['height' => 60]);
                },
                'filter' => false,
            ],
            'Price',

            ['class' => 'app\components\GridView\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?>

modules/Jalousie/views/model/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\bootstrap\Tabs;

/* @var $this yii\web\View */
/* @var $model app\modules\Jalousie\models\Model */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="color-form">
    
    <?php $form = ActiveForm::begin([
        'options' => [
            'enctype' => 'multipart/form-data'
        ]
    ]); ?>
    
    <?php
    
        $items = [
            [
                'label' => Yii::t('app', 'Date generale'),
                'content' => $this->render('_main_form', [
                    'form' => $form,
                    'model' => $model,
                ]),
                'active' => true,
            ],
            [
                'label' => Yii::t('app', 'Descriere'),
                'content' => $this->render('_languages_form', [
                    'form' => $form,
                    'model' => $model,
                ]),
            ],
        ];
        
        if (!$model->isNewRecord)
        {
            $items[] = [
                'label' => Yii::t('app', 'Colors'),
                'content' => $this->render('_colors_form', [
                    'form' => $form,
                    'model' => $model,
                    'searchModel'  => $searchModel,
                    'dataProvider' => $dataProvider,
                ]),
            ];
        }
    
    ?>
    
        <?= Tabs::widget([
            'items' => $items,
        ]); ?>


        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>

    <?php ActiveForm::end(); ?>

</div>

<?php if (Yii::$app->request->get('tab', false) == 'colors') { ?>
<?php $this->registerJs("
    $('.color-form #w7 li:last a').click();
"); ?>
<?php } ?>

modules/Jalousie/views/model/_language_form.php
<br />

<?= $form->field($langModel, "[$key]Title")->textInput() ?>

<?= $form->field($langModel, "[$key]Text")->textInput() ?>

modules/Jalousie/views/model/_languages_form.php
<?php

    use yii\bootstrap\Tabs;
    
    $items = [];
    foreach ($model->langs as $key => $langModel)
    {
        $items[] = [
            'label' => strtoupper($langModel->LangID),
            'content' => $this->render('_language_form', [
                'form' => $form,
                'langModel' => $langModel,
                'key' => $key,
            ]),
            'active' => $key === 0,
        ];
    }

?>

<br />

<?= Tabs::widget([
    'items' => $items,
]) ?>

modules/Jalousie/views/model/_main_form.php
<?php

    use yii\bootstrap\Html;
    use kartik\file\FileInput;
    use app\modules\Jalousie\models\Jalousie;
    
    $initialPreview = [];
    if ($model->imagePath)
    {
        $initialPreview[] = Html::img($model->imagePath, ['width' => 160]);
    }

?>

<br />

<div class="row">
    <div class="col-md-6">
        <label>Image</label>
        <?= FileInput::widget([
            'name' => 'Image',
            'options' => ['accept' => 'image/*'],
            'pluginOptions' => [
                'showRemove' => false,
                'showUpload' => false,
                'initialPreview' => $initialPreview,
            ]
        ]) ?>
    </div>
    <div class="col-md-6">
        
        <?= $form->field($model, 'JalousieID')->dropdownList(Jalousie::getList('-')) ?>
        
        <?= $form->field($model, 'Price')->textInput(['type' => 'number', 'min' => 0, 'step' => 0.01]) ?>
        
    </div>
</div>
<br />

modules/Jalousie/views/model/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\Windowsill\models\WindowsillColorSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="windowsill-color-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ID') ?>

    <?= $form->field($model, 'Image') ?>

    <?= $form->field($model, 'Price') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/Jalousie/views/model/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\Jalousie\models\Model */

$this->title = Yii::t('app', 'Create Model');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Models'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="windowsill-color-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/Jalousie/views/model/index.php
<?php

use yii\helpers\Html;
use app\components\GridView\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\Model\models\ModelSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Models');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="color-index">

    <h1><?= Html::encode($this->title) ?></h1>
    
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Model'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    
    <?php Pjax::begin(); ?>    
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            //'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                [
                    'attribute' => 'Image',
                    'format' => 'raw',
                    'value' => function($model)
                    {
                        return Html::img($model->imagePath, ['height' => 60]);
                    },
                    'filter' => false,
                ],
                [
                    'attribute' => 'jalousie.lang.Title',
                    'label' => 'Jalousie',
                ],
                'lang.Title',
                'Price',

                ['class' => 'app\components\GridView\ActionColumn'],
            ],
        ]); ?>
    <?php Pjax::end(); ?>

</div>

modules/Jalousie/views/model/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\Windowsill\models\WindowsillColor */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Model',
]) . $model->ID;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Models'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->ID, 'url' => ['view', 'id' => $model->ID]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="windowsill-color-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'searchModel'  => $searchModel,
        'dataProvider' => $dataProvider,
    ]) ?>

</div>

modules/Jalousie/views/model/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\Windowsill\models\WindowsillColor */

$this->title = $model->ID;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Windowsill Colors'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="windowsill-color-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->ID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->ID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'ID',
            'Image',
            'Price',
        ],
    ]) ?>

</div>